runtime: python39
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

entrypoint: gunicorn -b :$PORT fteback.wsgi:application

env_variables:
  DJANGO_SETTINGS_MODULE: "fteback.settings_prod"

handlers:
- url: /static
  static_dir: staticfiles/
  secure: always

- url: /.*
  script: auto
  secure: always 