# Generated by Django 4.2.21 on 2025-06-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fteapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matricula",
            name="materias",
            field=models.ManyToManyField(
                related_name="matriculas", to="fteapp.materia"
            ),
        ),
        migrations.DeleteModel(
            name="MatriculaMateria",
        ),
    ]
