# Generated by Django 5.2.1 on 2025-06-16 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fteapp', '0002_matricula_materias_delete_matriculamateria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
