# Generated by Django 5.2.1 on 2025-06-16 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fteapp', '0003_remove_usuario_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='correo',
            new_name='email',
        ),
    ]
